### ISSUE TITLE
Generation of utt2systemID files

### ISSUE THREAD

**Issue by StefanGitHuber** [jefflai108/Attentive-Filtering-Network#4]
Hi Jeff,
I cannot conclude how you generate the utt2systemID files:

- 1. features/run_feature.sh
Generates the scp+ark files as usual.

- 2. assert/data_reader/convertID2index.py
Both functions convert_la() + convert_pa() generate the utt2index files.
The scp files where generated by run_feature.sh at step i.
But where do the utt2systemID files come from, how to you generate them, what do they contain?
Option a) You directly use the utt2systemID files contained in PA/ASVspoof2019_PA_asv_protocols or PA/ASVspoof2019_PA_cm_protocols?
Option b) You have a script which parses these ASV/CM protocols into utterance ID and system ID?

- 3. data_files['eval_utt2systemID'] is not defined in my_config().data_files{}
After training with work() you call forward_pass() to conduct the evaluation.
At the end of forward_pass() you call 
    eval_prediction(eval_loader, model, device, score_file_pth, data_files['eval_utt2systemID'], use_rnn, focal_obj)
But 'eval_utt2systemID' is nowhere defined (just to tell).

Kind regards,

**Comment by jefflai108** [comment]
This is an snippet of utt2systemID: 
     1 LA_0069-LA_D_1047731 bonafide
     2 LA_0069-LA_D_1105538 bonafide
     3 LA_0069-LA_D_1125976 bonafide
     4 LA_0069-LA_D_1293230 bonafide
     5 LA_0069-LA_D_1340209 bonafide
     6 LA_0069-LA_D_1376638 bonafide
     7 LA_0069-LA_D_1377420 bonafide
     8 LA_0069-LA_D_1403371 bonafide
     9 LA_0069-LA_D_1590530 bonafide
    10 LA_0069-LA_D_1595036 bonafide
...
You can create this from the protocol file provided with a few lines of code. 

You can add 'eval_utt2systemID' to datafiles yourself. I must have deleted it somehow.
