### ISSUE TITLE
Missing files

### ISSUE THREAD

**Issue by samuel-peter** [jefflai108/Attentive-Filtering-Network#5]
When I try to run the code using ./run_feature.sh, I get the following error:

./run_feature.sh: line 5: ./cmd.sh: No such file or directory
./run_feature.sh: line 6: ./path.sh: No such file or directory
./run_feature.sh: line 21: utils/fix_data_dir.sh: No such file or directory

Where do I get these files from?
Kindly update the instructions in the README file accordingly.

**Comment by StefanGitHuber** [comment]
You get these files from the Kaldi toolkit.
It is mentioned in the README.
You may want to read and understand how to set up Kaldi at your environment reading an older issue reported here: https://github.com/jefflai108/Attentive-Filtering-Network/issues/2
