### ISSUE TITLE
which dataset.py is used

### ISSUE THREAD

**Issue by LeoMax-Xiong** [jefflai108/Attentive-Filtering-Network#7]
Hi, 
when I run the code, I find that there are 9 dataset.py, that is v1_dataset.py ~ v9_dataset.py，
In the git code, main.py use v3_dataset.py to read the train set,
but v3_dataset.py has no code to reshape feature to [1091, 257]。
please give some guide to use which dataset.py

**Comment by LeoMax-Xiong** [comment]
Hi, I run the scripts and use the CAttenNet, I get the result as this: Eval eer is always larger than 13% 。
===> Validation set: Average loss: 0.1215	EER: 4.3206
===> evalidation set: Average loss: 0.8836	EER: 15.4397
===> Validation set: Average loss: 0.8836	EER: 15.439
===> Validation set: Average loss: 0.1966	EER: 5.5330
===> evalidation set: Average loss: 1.7949	EER: 21.4176
===> Validation set: Average loss: 0.2288	EER: 4.1896
===> evalidation set: Average loss: 1.9633	EER: 15.7935
===> Validation set: Average loss: 0.1529	EER: 3.8001
===> evalidation set: Average loss: 1.3544	EER: 16.1017
===> Validation set: Average loss: 0.2217	EER: 3.6615
===> evalidation set: Average loss: 1.8525	EER: 14.8484
===> Validation set: Average loss: 0.3128	EER: 3.9870
===> evalidation set: Average loss: 2.3662	EER: 15.8706
===> Validation set: Average loss: 0.2874	EER: 3.8649
===> evalidation set: Average loss: 1.9526	EER: 14.8690
===> Validation set: Average loss: 0.3360	EER: 3.6615
===> evalidation set: Average loss: 2.2905	EER: 14.8313
===> Validation set: Average loss: 0.3263	EER: 3.7478
===> evalidation set: Average loss: 2.2401	EER: 14.6379
===> Validation set: Average loss: 0.3659	EER: 3.5714
===> evalidation set: Average loss: 2.5050	EER: 14.2570
===> Validation set: Average loss: 0.2109	EER: 3.3532
===> evalidation set: Average loss: 1.6002	EER: 13.3984
===> Validation set: Average loss: 0.3679	EER: 3.6608
===> evalidation set: Average loss: 2.5162	EER: 13.8675
===> Validation set: Average loss: 0.2920	EER: 3.5801
===> evalidation set: Average loss: 2.1610	EER: 13.9186
===> Validation set: Average loss: 0.3828	EER: 3.4601
===> evalidation set: Average loss: 2.6925	EER: 14.0448
===> Validation set: Average loss: 0.2259	EER: 3.3510
===> evalidation set: Average loss: 1.7532	EER: 13.4660
===> Validation set: Average loss: 0.3302	EER: 3.3951
===> evalidation set: Average loss: 2.3690	EER: 14.0989
===> Validation set: Average loss: 0.3522	EER: 3.3767
===> evalidation set: Average loss: 2.4965	EER: 13.8957
===> Validation set: Average loss: 0.3221	EER: 3.4581
===> evalidation set: Average loss: 2.3104	EER: 13.9490
===> Validation set: Average loss: 0.3885	EER: 3.5273
===> evalidation set: Average loss: 2.6712	EER: 14.2234
===> Validation set: Average loss: 0.3535	EER: 3.4225
===> evalidation set: Average loss: 2.4902	EER: 13.8658

**Comment by jefflai108** [comment]
Hi @Honei 
this repo is a bit messy and thus there are many redundant code and models. Try the models in this repo instead: `https://github.com/jefflai108/Attentive-Filtering-Network/blob/master/src/attention_neuro/simple_attention_network.py`

there are convergence issues (see #2 ). This may have to do with the dataset is small and the model training is thus unstable.
